# -*- coding: utf-8 -*-
"""5.1 파이썬 EDA-pandas-input.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t-EbhbgZMdpqJXOgTxj4nIjob8vyUmU9

## 라이브러리 로드
"""

# 데이터 분석을 위한 pandas 라이브러리를 불러옵니다.
# 데이터 시각화를 위한 seaborn 을 불러옵니다.
import pandas as pd
import seaborn as sns

print(pd.__version__)
print(sns.__version__)

# 0.11.0 버전에서 변화가 많으니 이 버전 이상을 사용해 주세요. 
# !pip install seaborn --upgrade

"""## 데이터셋 불러오기
<img src="https://pandas.pydata.org/docs/_images/02_io_readwrite.svg">

* seaborn 데이터셋 위치 : https://github.com/mwaskom/seaborn-data
"""

# df
#sns.load_dataset("mpg")
df= pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/mpg.csv")
df. shape

# index 값만 보기
df.index

# columns 값만 보기
df.columns

# values 값만 보기
df.values

# 데이터 타입만 보기
df.dtypes

"""## 데이터셋 일부만 가져오기"""

# head 을 통해 일부만 가져오기
df.head()

# tail 을 통해 일부만 가져오기
df.tail(2)

# sample을 통해 일부만 가져오기
df.sample(3, random_state= 42)

"""## 요약하기"""

# info 를 통해 요약정보 보기
df.info()

"""## 결측치 확인"""

# 결측치 수 확인
df.isna(). sum()

# 결측치 비율 확인
df. isna(). mean() *100

"""## 기술통계"""

# describe 로 기술통계 확인하기
df. describe()

df.describe(include = "object")

"""## Series"""

df["mpg"]

type(df["mpg"])

"""## DataFrame"""

type(df)

"""## 색인하기

* 열(column) 인덱싱
* [컬럼]
* [[컬럼1, 컬럼2, 컬럼3]]
"""

df["name"]

df[["name"]]

df[["origin", "name"]]

"""## loc
* 행(index) 인덱싱
* .loc[행]
* .loc[행, 열]
* .loc[조건식, 열]

"""

# loc 로 하나의 행을 가져옵니다.
# loc == locate
df.loc[0]

# loc로 2개의 행을 가져와 봅니다.
df.loc[[0, 1]]

# loc로 행, 열을 가져와 봅니다.
df.loc[0, "name"]

# loc로 여러개의 행, 열을 가져와 봅니다.
df.loc[[0,1], ["name", "origin"]]

