# -*- coding: utf-8 -*-
"""5.2 파이썬 EDA-기술통계-input.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VaQvC-VBFl5TRFKYtbwHAG5rU8Qw-CSd

## 라이브러리 로드
"""

# 데이터 분석을 위한 pandas 라이브러리를 불러옵니다.
# 데이터 시각화를 위한 seaborn 을 불러옵니다.
import pandas as pd
import seaborn as sns

print(pd.__version__)
print(sns.__version__)

# 0.11.0 버전에서 변화가 많으니 이 버전 이상을 사용해 주세요. 
# !pip install seaborn --upgrade

"""## 데이터셋 불러오기
<img src="https://pandas.pydata.org/docs/_images/02_io_readwrite.svg">

* seaborn 데이터셋 위치 : https://github.com/mwaskom/seaborn-data
"""

df = sns.load_dataset("mpg")
df .shape

"""## 데이터셋 일부만 가져오기"""

# head
df .head()

# tail
df .tail()

# sample
df. sample()

"""## 매번 봐야 하는 기술통계값 코드 한 줄로 보기 
### Pandas Profiling
* [pandas-profiling/pandas-profiling: Create HTML profiling reports from pandas DataFrame objects](https://github.com/pandas-profiling/pandas-profiling)
"""

# 아래 명령어로 설치합니다.
# 2.8.0 이상 버전에서 폰트 설정방법이 변경되어 아래 버전을 사용을 추천합니다.
!pip install pandas_profiling==2.8.0

from pandas_profiling import ProfileReport
profile = ProfileReport(df, title="Pandas Profiling Report")

# 주피터 노트북이 있는 위치에 html파일이 생성됩니다.
profile.to_file("pandas_profile_report.html")

"""### sweetviz
* [sweetviz · PyPI](https://pypi.org/project/sweetviz/)
<img src="https://warehouse-camo.ingress.cmh1.psfhosted.org/210c4eb7317c8b0d2e7d0784b1a9697c096050ef/687474703a2f2f636f6f6c74696d696e672e636f6d2f53562f4c61796f75742d416e696d332e676966">
"""

# 아래 명령어로 설치해 주셔야지 사용할 수 있습니다.
!pip install sweetviz

import sweetviz as sv

my_report = sv.analyze(df)
# 타겟변수 없이 그릴 수도 있고 타겟변수를 지정할 수도 있습니다.
# 타겟변수는 범주형이 아닌 수치, bool 값만 가능합니다. 
# 데이터에 따라 수치형으로 되어있지만 동작하지 않을 수도 있습니다. 
# my_report = sv.analyze(df, target_feat ='mpg')
my_report.show_html()







